### PR TITLE
Importing a new db from ONSPD and OSNI

### PR DESCRIPTION
**Pull request by h-lame**
For: https://trello.com/c/a7c1LPbl/26-get-mapit-database-onto-new-preview-machine

This PR contains work we had to do to import new data from ONSPD and use the boundaries for the redone NI councils created in April 2015.  We built new importers and pushed that work upstream to mysociety (see: mysociety/mapit#216).  Although that PR was closed unmerged, all the work was merged separately (some of it squashed down).  This PR merges the current upstream master (see merge-commit 4e0e3fadef8fae2992183fd504d8fd4fb1fa82cb towards the end of this PR).  The other commits are a couple of extra importers useful for us, but not upstream.

There is a PR open against our [mapit-scripts](https://github.gds/gds/mapit-scripts/) repo that lets us automate running all these importers to build a fresh DB. See: https://github.gds/gds/mapit-scripts/pull/2

We also have a PR open against our [opsmanual](https://github.gds/gds/opsmanual/) repo to describe how to run these scripts and what effort must be taken when importing a new datase.  See: https://github.gds/gds/opsmanual/pull/603

Note: a previous version of this PR included a "show your working" version of the mysociety/mapit#216 PR.  Now that it's merged, we've redone to only include the merge.

### CODE REVIEW

**Comment by h-lame** [comment]
Note that some import scripts for our mapit exist in https://github.gds/gds/mapit-scripts/ and there is a PR there for using some of the new commands we add in this PR (see: https://github.gds/gds/mapit-scripts/pull/2)

**Comment by h-lame** [comment]
Note that this PR includes work we'd like to push upstream back to mysociety.  That work lives in https://github.com/mysociety/mapit/pull/216 and we'll do some commit / branch juggling if that is merged.

**Comment by h-lame** [comment]
Note that the work we've provided in a PR to the upstream repo is a condensed version of this work to remove our "show your working" commits (e.g. the import NI areas from a fixture stuff and squash down the no_location stuff).  When (if) that is merged the rejig to incorporate that work will be a little complex.

**Comment by davidbasalla** [comment]
Having looked at the last 2 commits, they make sense to me. It's probably worth other people with either more context and/or more knowledge about Python/Django having a look before this gets merged?

**Comment by h-lame** [comment]
:sparkles: woo :dancers: excite :fireworks: &c &c &c

**Comment by sihugh** [comment]
:clap:

**Pull request merged**
