### PR TITLE
Revert "Open CSV files with the correct encoding"

### PR DESCRIPTION
**Pull request by davidbasalla**
This reverts commit 4268f1d0b7458bdf006c5e505d223ffb08cfcbbd.

The change breaks the import for us when running with Python 2.7 by failing to
recognise a Welsh character. The change was added for use with Python 3 which
we do not use, so can ignore this.

See https://github.com/mysociety/mapit/pull/225

### CODE REVIEW

**Comment by sihugh** [comment]
Looks good to me, but I worked with David on this a bit, so probably shouldn't merge.

**Comment by jennyd** [comment]
I'm somewhat confused by this. Before reverting this it errors on `ô` and `â`, both of which are [in latin-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) (as `00F4` and `00E2` respectively), so opening the file with `latin-1` should work fine, as far as I can tell. The error I get sounds like it's trying to use `ascii` instead of `latin-1`, though:

```

Reverting this commit stops it erroring, and we aren't using the name fields from either file so .

**Comment by sihugh** [comment]
https://docs.python.org/2/library/codecs.html implies that the `latin-1` codec is `latin_1` (with aliases `iso-8859-1`, `iso8859-1`, `8859`, `cp819`, `latin`, `latin1`, `L1`.  Can we try one of these instead?

**Comment by jennyd** [comment]
The encoding problem is down to `csv.reader` changing between Python 2 and 3 - in 2 it expected a file-like object on which `next()` would return raw bytes, and in 3 one which would return unicode strings. That means it's awkward to write code to handle CSV files which is compatible with both Python 2 and 3.

The simplest thing to do in our case is to [explicitly check the Python version](http://stackoverflow.com/questions/5180555/python-2-and-3-csv-reader/5181085#5181085), and open the file in the original way for 2 and with `latin-1` for 3. We don't need the names in this script, so any encoding errors in them shouldn't matter. We should push this fix upstream too.

**Comment by davidbasalla** [comment]
Closed in favour of https://github.com/alphagov/mapit/pull/25

**Pull request closed without merging**
