### PR TITLE
Allow updating locationless postcodes

### PR DESCRIPTION
**Pull request by issyl0**
- We needed to import a postcode apparently without a location, and
  the import was failing on this one specific postcode (HD7 9AS)
  because `pc.location` was blank. We've made this check more robust,
  and in the case where a postcode is blank, we've saved it anyway
  with the `location` data that comes from the file.

This was found while importing February's postcode data. Thanks to @h-lame for the help tracking down why!

Best reviewed with `?w=1`.

### CODE REVIEW

**Comment by sihugh** [comment]
Why don't MySociety have this problem?  I was wondering whether this could be contributed back, but they appear to cope with the example postcode OK.  (Solution seems fine for the problem btw :-) )

https://github.com/mysociety/mapit/blob/master/mapit/management/commands/mapit_import_postal_codes.py#L133

https://mapit.mysociety.org/postcode/HD7%209AS

**Comment by h-lame** [comment]
@sihugh they would have this problem if they imported locationless postcodes like we do, but I don't think they do.  So when a previously locationless postcode gets an "upgrade" to have a location they see it as a new postcode, whereas we saw it as an update and fell over without this fix.  We absolutely should push this upstream. 

We probably don't want to merge this PR, but review it for "ok" then redo a PR against their version and when (if) that gets merged opening a PR on our version to pull in latest upstream changes, including our fix.  Complicated.

**Comment by sihugh** [comment]
Well this gets my :+1:

**Comment by dracos** [comment]
Looks good to me :) Cherry picked upstream as 92fd6c3b3c5bb1fc952e0800812426aa1c115789 (sorry for any presumption, but as I saw it I thought I might as well!).

**Pull request closed without merging**
